

package userinterface.RestaurantAdminRole;


import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Menu.MenuDirectory;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
   private JPanel userProcessContainer;
   private UserAccount useraccount;
   private EcoSystem ecosystem;
   private CustomerDirectory customerdirectory;
   private RestaurantDirectory restaurantdirectory;
   private DeliveryManDirectory delivermanDirectory;
   private MenuDirectory menudirectory;
   private OrderDirectory orderdirectory;
    
     
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,  UserAccount useraccount,
    EcoSystem ecosystem,
    CustomerDirectory customerdirectory,
    RestaurantDirectory restaurantdirectory,
    DeliveryManDirectory delivermanDirectory,
    MenuDirectory menudirectory,
    OrderDirectory orderdirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount=useraccount;
        this.ecosystem=ecosystem;
        this.customerdirectory=customerdirectory;
        this.restaurantdirectory=restaurantdirectory;
        this.delivermanDirectory=delivermanDirectory;
        this.menudirectory=menudirectory;
        this.orderdirectory=orderdirectory;
        valueLabel.setText(useraccount.getUsername());
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    //public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, CustomerDirectory customerDirectory, RestaurantDirectory restaurantDirectory, DeliveryManDirectory deliveryManDirectory, MenuDirectory menuDirectory, OrderDirectory orderDirectory) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(151, 145, 151));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        userJButton.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        userJButton.setText("RESTAURANT");
        userJButton.setBorder(new javax.swing.border.MatteBorder(null));
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 20));

        manageEmployeeJButton.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        manageEmployeeJButton.setText("MENU");
        manageEmployeeJButton.setBorder(new javax.swing.border.MatteBorder(null));
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, 20));

        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        manageOrganizationJButton.setText("ORDERS");
        manageOrganizationJButton.setBorder(new javax.swing.border.MatteBorder(null));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 20));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterpriseLabel.setText("RESTAURANT");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageRestaurantInfoJPanel manresinfopan=new ManageRestaurantInfoJPanel(userProcessContainer,useraccount,ecosystem,restaurantdirectory);
        userProcessContainer.add("manageMenuJPanel",manresinfopan);
        CardLayout crdlout=(CardLayout) userProcessContainer.getLayout();
        crdlout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageMenuJPanel manmenu=new ManageMenuJPanel(userProcessContainer,useraccount,ecosystem,restaurantdirectory,menudirectory);
        userProcessContainer.add("manageMenuPanel",manmenu);
        CardLayout crdlout=(CardLayout) userProcessContainer.getLayout();
        crdlout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrderJPanel manorder=new ManageOrderJPanel(userProcessContainer,useraccount,ecosystem,restaurantdirectory,menudirectory, orderdirectory);
        userProcessContainer.add("ManageOrderPanel",manorder);
        CardLayout crdlout=(CardLayout) userProcessContainer.getLayout();
        crdlout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
