/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Divya Sharma
 */
public class ManageRestaurantInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantInfoJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private EcoSystem ecosystem;
    private RestaurantDirectory restaurantdirectory;
    private Restaurant restaurant;
    
    
    
    public ManageRestaurantInfoJPanel(JPanel userProcessContainer, UserAccount useraccount, EcoSystem ecosystem, RestaurantDirectory restaurantdirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.ecosystem = ecosystem;
        this.restaurantdirectory = ecosystem.getRestaurantDirectory();
        System.out.println(restaurantdirectory.getRestaurantDirectory().size() + "   ...... ");
        for(Restaurant res : this.restaurantdirectory.getRestaurantDirectory()) {
            System.out.println(res.getRestaurantName() + " " + useraccount.getEmployee().getName());
            if(useraccount.getEmployee().getName().equals(res.getRestaurantName())) {
                this.restaurant = res;
                break;
            }
        }
        populateTable();
    }
    
     public void populateTable() {
        DefaultTableModel deftabmdl = (DefaultTableModel) tblRestaurant.getModel();
        deftabmdl.setRowCount(0);
        Object [] row = new Object[4];
        row[0] = restaurant;
        row[1] = restaurant.getAddress();
        row[2] = restaurant.getManagerName();
        row[3] = restaurant.getPhoneNumber();
        
        deftabmdl.addRow(row);
    }
     
     public void refreshTable() {
        DefaultTableModel deftabmdl = (DefaultTableModel) tblRestaurant.getModel();
        deftabmdl.setRowCount(0);
        
        Object [] row = new Object[4];
        row[0] = restaurant;
        row[1] = restaurant.getAddress();
        row[2] = restaurant.getManagerName();
        row[3] = restaurant.getPhoneNumber();
        deftabmdl.addRow(row);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleManageRes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurant = new javax.swing.JTable();
        btnBackMR = new javax.swing.JButton();
        btnModifyMR = new javax.swing.JButton();

        setBackground(new java.awt.Color(151, 145, 151));

        titleManageRes.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titleManageRes.setForeground(new java.awt.Color(255, 255, 255));
        titleManageRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageRes.setText("MANAGE RESTAURANT");

        tblRestaurant.setBorder(new javax.swing.border.MatteBorder(null));
        tblRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RESTAURANT ", "ADDRESS", "MANAGER", "CONTACT"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurant);

        btnBackMR.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnBackMR.setText("BACK");
        btnBackMR.setBorder(new javax.swing.border.MatteBorder(null));
        btnBackMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMRActionPerformed(evt);
            }
        });

        btnModifyMR.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnModifyMR.setText("MODIFY");
        btnModifyMR.setBorder(new javax.swing.border.MatteBorder(null));
        btnModifyMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnBackMR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(btnModifyMR, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleManageRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleManageRes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackMR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnModifyMR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMRActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRestaurant.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Restaurant restaurant = (Restaurant)tblRestaurant.getValueAt(selectedRow,0);
        ModifyRestaurantInfoJPanel modifyManager = new ModifyRestaurantInfoJPanel(userProcessContainer, ecosystem, restaurantdirectory, restaurant);
        userProcessContainer.add("ModifyRestaurantInfoJPanel",modifyManager);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModifyMRActionPerformed

    private void btnBackMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMRActionPerformed
                                              
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
                
    }//GEN-LAST:event_btnBackMRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMR;
    private javax.swing.JButton btnModifyMR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRestaurant;
    private javax.swing.JLabel titleManageRes;
    // End of variables declaration//GEN-END:variables
}
