/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Menu.MenuDirectory;
import Business.Order.Order;
import Business.Order.OrderStatus;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Divya Sharma
 * @author charusingh
 */
public class ManageVaccineRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private EcoSystem ecosystem;
    private RestaurantDirectory restaurantdirectory;
    private MenuDirectory menudirectory;
    private OrderDirectory orderdirectory;
    private DeliveryManDirectory deliverymandirectory;

    public ManageVaccineRequestJPanel(JPanel userProcessContainer, UserAccount useraccount, EcoSystem ecosystem, RestaurantDirectory restaurantdirectory, MenuDirectory menudirectory, OrderDirectory orderdirectory) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.useraccount = useraccount;
        this.restaurantdirectory = ecosystem.getRestaurantDirectory();
        this.menudirectory = ecosystem.getMenuDirectory();
        this.orderdirectory = ecosystem.getOrderDirectory();
        this.deliverymandirectory = ecosystem.getDeliveryManDirectory();
        
        populateTable();
        populateRestaurantCombo();
    }

    public void populateTable() {
        DefaultTableModel deftabmdl = (DefaultTableModel) tblOrder.getModel();
        deftabmdl.setRowCount(0);

        for (Order order : ecosystem.getOrderDirectory().getOrderDirectory()) 
        {
            System.out.println(" Rest  " + useraccount.getEmployee().getName() + "  " + order.getRestaurant().getRestaurantName());
            if (useraccount.getEmployee().getName().equals(order.getRestaurant().getRestaurantName())) {
                Object[] row = new Object[5];
                row[0] = order;
                row[1] = order.getMenu().getItemName();
                row[2] = order.getMenu().getPrice();
                row[3] = order.getOrderStatus();
                deftabmdl.addRow(row);
            }
        }
    }

    public final void populateRestaurantCombo() {

        comboDelivery.removeAll();
        comboDelivery.addItem(" ");
        for (DeliveryMan deliveryman : deliverymandirectory.getDeliveryManDirectory()) {
            comboDelivery.addItem(deliveryman.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleManageOrder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnBackMO = new javax.swing.JButton();
        btnAcceptMO = new javax.swing.JButton();
        btnCompleteMO = new javax.swing.JButton();
        comboDelivery = new javax.swing.JComboBox<>();
        lblAssignDelivery = new javax.swing.JLabel();
        btnAssignDelivery = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(151, 145, 151));
        setPreferredSize(new java.awt.Dimension(1680, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleManageOrder.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titleManageOrder.setForeground(new java.awt.Color(51, 51, 51));
        titleManageOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageOrder.setText("VACCINE REQUESTS");
        add(titleManageOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 370, -1));

        tblOrder.setBorder(new javax.swing.border.MatteBorder(null));
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PATIENT ID", "VACCINE NAME", "DOSES REQUIRED", " STATUS"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 719, 103));

        btnBackMO.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnBackMO.setText("BACK");
        btnBackMO.setBorder(new javax.swing.border.MatteBorder(null));
        btnBackMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMOActionPerformed(evt);
            }
        });
        add(btnBackMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 71, 22));

        btnAcceptMO.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnAcceptMO.setText("CONFIRM");
        btnAcceptMO.setBorder(new javax.swing.border.MatteBorder(null));
        btnAcceptMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptMOActionPerformed(evt);
            }
        });
        add(btnAcceptMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 83, 24));

        btnCompleteMO.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnCompleteMO.setText("PROCESS REQUEST");
        btnCompleteMO.setBorder(new javax.swing.border.MatteBorder(null));
        btnCompleteMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteMOActionPerformed(evt);
            }
        });
        add(btnCompleteMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 160, 24));

        add(comboDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 143, -1));

        lblAssignDelivery.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblAssignDelivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssignDelivery.setText("Assign request to available Pharmacy :");
        add(lblAssignDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 290, 30));

        btnAssignDelivery.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnAssignDelivery.setText("ASSIGN");
        btnAssignDelivery.setBorder(new javax.swing.border.MatteBorder(null));
        btnAssignDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDeliveryActionPerformed(evt);
            }
        });
        add(btnAssignDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 80, 22));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Hospital.jpeg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1680, 700));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 20, 1680, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteMOActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to proceed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Order order = (Order) tblOrder.getValueAt(selectedRow, 0);
        if (order.getOrderStatus().equals(OrderStatus.Awaiting_Approval.getValue())) {
            order.setOrderStatus(OrderStatus.Vaccine_Approved.getValue());
            JOptionPane.showMessageDialog(null, "Request approved. Now assign to pharmacy.");
            order.setAssign(true);
        } else if (order.getOrderStatus().equals(OrderStatus.Vaccine_Requested.getValue())) {
            JOptionPane.showMessageDialog(null, "Accept request in order to approve.");
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Request already approved. ");
            return;
        }

        populateTable();
    }//GEN-LAST:event_btnCompleteMOActionPerformed

    private void btnAcceptMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptMOActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a record to proceed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Order order = (Order) tblOrder.getValueAt(selectedRow, 0);

        if (order.getOrderStatus().equals(OrderStatus.Vaccine_Requested.getValue())) {
            order.setOrderStatus(OrderStatus.Awaiting_Approval.getValue());
            JOptionPane.showMessageDialog(null, "Vaccine request accepted. Arrange approvals to proceed further.");
        } 
        else if (order.getOrderStatus().equals(OrderStatus.Awaiting_Approval.getValue())){
            JOptionPane.showMessageDialog(null, "Request already accepted.");
            return;
        }

        populateTable();
    }//GEN-LAST:event_btnAcceptMOActionPerformed

    private void btnBackMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMOActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackMOActionPerformed

    private void btnAssignDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDeliveryActionPerformed
        // TODO add your handling code here:int selectedRow = tblOrder.getSelectedRow();
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        Order order = (Order) tblOrder.getValueAt(selectedRow, 0);
        if (comboDelivery.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select you preferred pharmacy.");
            return;
        }
        if (order.getOrderStatus().equals(OrderStatus.Vaccine_Approved.getValue())) {
            for (DeliveryMan deliveryman : deliverymandirectory.getDeliveryManDirectory()) {
                if (deliveryman.getName().equals(comboDelivery.getSelectedItem())) {
                    order.setDeliveryMan(deliveryman.getEmail());
                }
            }
            order.setOrderStatus(OrderStatus.Vaccine_Assigned.getValue());
            JOptionPane.showMessageDialog(null, "Request assigned successfully");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Request needs to be Accepted and Approved before assignment.");
            return;
        }
    }//GEN-LAST:event_btnAssignDeliveryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptMO;
    private javax.swing.JButton btnAssignDelivery;
    private javax.swing.JButton btnBackMO;
    private javax.swing.JButton btnCompleteMO;
    private javax.swing.JComboBox<String> comboDelivery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssignDelivery;
    private javax.swing.JTable tblOrder;
    private javax.swing.JLabel titleManageOrder;
    // End of variables declaration//GEN-END:variables
}
