/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Menu.MenuDirectory;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Divya Sharma
 */
public class ManageVaccinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenuJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private EcoSystem ecosystem;
    private RestaurantDirectory restaurantdirectory;
    private MenuDirectory menudirectory;
    private Restaurant restaurant;
    
    
    public ManageVaccinesJPanel(JPanel userProcessContainer, UserAccount useraccount, EcoSystem ecosystem, 
                             RestaurantDirectory restaurantdirectory, MenuDirectory menudirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.ecosystem = ecosystem;
        this.restaurantdirectory = ecosystem.getRestaurantDirectory();
        this.menudirectory = ecosystem.getMenuDirectory();
        populateTable();
    }
    
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblManMenuIP.getModel();
        dtm.setRowCount(0);
        for(Menu menu : menudirectory.getMenuDirectory()){
            if(menu.getRestaurantName().equals(useraccount.getEmployee().getName())) {
                Object [] row = new Object[2];
                row[0] = menu;
                row[1] = menu.getPrice();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManMenuIP = new javax.swing.JTable();
        titleManageMenu = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        titleAddItem = new javax.swing.JLabel();
        lblIN = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtIN = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(151, 145, 151));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblManMenuIP.setBorder(new javax.swing.border.MatteBorder(null));
        tblManMenuIP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "VACCINE PROVIDER", "DOSES REQUIRED"
            }
        ));
        jScrollPane1.setViewportView(tblManMenuIP);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 132, -1, 108));

        titleManageMenu.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        titleManageMenu.setForeground(new java.awt.Color(255, 255, 255));
        titleManageMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleManageMenu.setText("MANAGE VACCINES");
        add(titleManageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, 744, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 76, 75, 23));

        titleAddItem.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        titleAddItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAddItem.setText("ADD VACCINES");
        add(titleAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 301, 744, -1));

        lblIN.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        lblIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIN.setText("VACCINE PROVIDER");
        add(lblIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 364, 109, 20));

        lblPrice.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setText("DOSES REQUIRED");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 414, 109, 20));

        txtIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 364, 91, -1));

        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 414, 91, -1));

        btnAddItem.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        btnAddItem.setText("ADD");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        add(btnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 74, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Hospital.jpeg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1680, 700));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 1680, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        
        if(txtIN.getText().isEmpty() || txtPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty");
            return;
        }
        
        String itemName = txtIN.getText();
        double price;
        try {
            price = Double.parseDouble(txtPrice.getText());
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Doses required should be a numeric value.");
            return;
        }
        
        String res = useraccount.getEmployee().getName();
        
        menudirectory.newItem(itemName, price, res);
        populateTable();
        
        clearAll();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void clearAll() {
        
        txtIN.setText("");
        txtPrice.setText("");
        
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIN;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTable tblManMenuIP;
    private javax.swing.JLabel titleAddItem;
    private javax.swing.JLabel titleManageMenu;
    private javax.swing.JTextField txtIN;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
